version: "3"
services:
  jenkins:
    build:
      context: ./jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/hafner/Development/jenkins-home-docker:/var/jenkins_home
    ports:
      - 8081:8080
    environment:
      - VIRTUAL_HOST=jenkins.local
      - VIRTUAL_PORT=8081
      - TRY_UPGRADE_IF_NO_MARKER=true
    restart: always
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    restart: always
