jenkins:
  systemMessage: "<h1>Warnings Next Generation Plugin Showcase</h1>"
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 1
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"

tool:
  git:
    installations:
    - home: "git"
      name: "git-default"
  maven:
    installations:
    - name: "mvn-default"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.6.0"
jobs:
  - script: >
      pipelineJob('pipeline-analysis-model') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile.local'
                  scm {
                    git {
                        remote { url 'https://github.com/jenkinsci/analysis-model.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      };
      pipelineJob('pipeline-warnings-ng') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile.local'
                  scm {
                    git {
                        remote { url 'https://github.com/jenkinsci/warnings-ng-plugin.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      };
      job('freestyle-analysis-model') {
        scm {
            git("https://github.com/jenkinsci/analysis-model.git")
        }
        steps {
            maven {
                mavenInstallation('3.6.0')
                rootPOM("${projectDir}/pom.xml")
                goals('verify')
            }
        }
        publishers {
            archiveJunit("${projectDir}/**/surefire-reports/*.xml")
        }
      };
