jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  mode: NORMAL
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
  slaveAgentPort: 50000
  systemMessage: "<h1>Warnings Next Generation Plugin Showcase</h1>"
  views:
  - all:
      name: "all"

unclassified:
  location:
    adminAddress: "Adresse nicht konfiguriert <nobody@nowhere>"
    url: "http://localhost:8081/"
  simple-theme-plugin:
    elements:
    - cssUrl:
        url: "http://localhost:8081/userContent/material-blue-grey.css"

tool:
  git:
    installations:
    - home: "git"
      name: "git-default"
  maven:
    installations:
    - name: "mvn-default"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.6.0"
  jdk:
    defaultProperties:
    - installSource:
        installers:
        - jdkInstaller:
            acceptLicense: false
  pipelineMaven:
    publisherOptions:
    - junitPublisher:
        disabled: true
        healthScaleFactor: !!int '1.0'

jobs:
  - script: >
      pipelineJob('pipeline-analysis-model') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile.local'
                  scm {
                    git {
                        remote { url 'https://github.com/jenkinsci/analysis-model.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      };
      pipelineJob('pipeline-warnings-ng') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile.local'
                  scm {
                    git {
                        remote { url 'https://github.com/jenkinsci/warnings-ng-plugin.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      };
      job('freestyle-analysis-model') {
        scm {
            git("https://github.com/jenkinsci/analysis-model.git")
        }
        steps {
            maven {
                mavenInstallation('3.6.0')
                rootPOM("${projectDir}/pom.xml")
                goals('verify')
            }
        }
        publishers {
            archiveJunit("${projectDir}/**/surefire-reports/*.xml")
        }
      };
